version: "3.7"
services:
  postgres:
    image: debezium/postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=exampledb
  pgadmin:
          image: dpage/pgadmin4
          environment: 
              - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
              - PGADMIN_DEFAULT_PASSWORD=admin1234
          ports:
              - '5050:80'
          restart: always
